version: '3'
services:
  serveur_ssh:
    build: ./serveur_ssh
    ports:
      - "22:22"
      
  raspberry_pi_1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pi_folder: pi1
    ports:
      - "8081:80"

  raspberry_pi_2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pi_folder: pi2
    ports:
      - "8082:80"

  raspberry_pi_3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pi_folder: pi3
    ports:
      - "8083:80"
