version: "3.8"
services:
  nodeserver:
    build:
      context: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeserver.rule=Host(`nodeserver.localhost`)"
      - "traefik.http.routers.nodeserver.entrypoints=websecure"
      - "traefik.http.routers.nodeserver.tls.certresolver=myresolver"
    ports:
      - "5000:5000"
    networks:
      - traefik_network

  db:
    image: mysql
    container_name: database
    command: 
        --default-authentication-plugin=mysql_native_password
        --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
        MYSQL_USER: mysql
        MYSQL_ROOT_PASSWORD: matias
    volumes:
        - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
        - traefik_network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
        - 8089:8080
    networks:
        - traefik_network
    
  traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"  
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contact@mon-domaine.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" 
      - "--accesslog=true"   # Activer les logs d'accès
      - "--accesslog.filepath=/var/log/traefik/access.log" 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./traefik/logs:/var/log/traefik"  
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge