version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
    traefik:
        image: "traefik:v2.11"
        container_name: "traefik"
        command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        ports:
        - "80:80"
        - "8080:8080"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
        - "traefik.http.routers.whoami.entrypoints=web"
    api-node:
        restart: always
        build:
            context: ./api-node/api-node
        ports:
            - "3000:3000"
      
    raspberry_pi_1:
        build:
            dockerfile: Dockerfile
            args:
                pi_folder: pi1
        ports:
        - "8081:80"

    raspberry_pi_2:
        build:
            dockerfile: Dockerfile
            args:
                pi_folder: pi2
        ports:
        - "8082:80"

    raspberry_pi_3:
        build:
            dockerfile: Dockerfile
            args:
                pi_folder: pi3
        ports:
        - "8083:80"

