version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
    db:
        image: mysql
        command: 
            --default-authentication-plugin=mysql_native_password 
            --init-file /docker-entrypoint-initdb.d/init.sql
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: matias
        volumes:
            - ./mysql-scripts:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    api-node:
        build:
            context: ./api-node/api-node
        ports:
            - "3000:3000"
      
    # raspberry_pi_1:
    #     build:
    #         dockerfile: Dockerfile
    #         args:
    #             pi_folder: pi1
    #     ports:
    #     - "8081:80"

    # raspberry_pi_2:
    #     build:
    #         dockerfile: Dockerfile
    #         args:
    #             pi_folder: pi2
    #     ports:
    #     - "8082:80"

    # raspberry_pi_3:
    #     build:
    #         dockerfile: Dockerfile
    #         args:
    #             pi_folder: pi3
    #     ports:
    #     - "8083:80"