version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
    api-node:
        restart: always
        build:
            context: ./api-node/api-node
        ports:
            - "3000:3000"

