[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

[api]
  dashboard = true
  insecure = true

[certificatesResolvers.myresolver.acme]
  email = "lopezetienne@wanadoo.fr"
  storage = "acme.json"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory" # CA server to use for staging = DEV
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"
